### PR TITLE
Add mention of Nexus with plugin to README

### LINKED ISSUE #861: Add example of nexus-graphql-shield to README?
In the README, there's mentions of Yoga and using `graphql-middleware`, but nothing mentioning how to use it with Nexus. Nexus is an actively maintained backend framework that integrates well with Prisma, while Yoga has not been actively maintained for over a year. There is a plugin called `nexus-graphql-shield` that does basic integration with Nexus, perhaps at least a mention or a code snippet could be put in the README to let visitors know that it supports integrating with Nexus?

Nexus plugin: https://github.com/lvauvillier/nexus-plugin-shield
Nexus: https://nexus.js.org/
Yoga deprecation: https://github.com/prisma-labs/graphql-yoga/issues/449

### PR DESCRIPTION
**Pull request by cktang88**
Closes #861

### CODE REVIEW

**Comment by maticzav** [comment]
Hey 👋 ,

This is awesome! One thing that I wondered; do you think it would be better to put `nexus` example behind the other examples? I was thinking the same thing with the overview bullet point. As far as I know, the nexus plugin stands on its own, and I wouldn't want to confuse people about the libraries.

**Comment by cktang88** [comment]
@maticzav will do!

**Comment by cktang88** [comment]
Actually due to https://github.com/prisma-labs/graphql-framework-experiment/issues/1432 this might not be super useful, lmk if you'd rather not make this change!

**Comment by maticzav** [comment]
Oh my 🙈 , I don't know how I feel about the news. Let's wait a bit and decide later. I think the plugin could still be useful since the plugin system works independently of the framework.

Thank you for opening the PR and bringing the news to me.

**Pull request closed without merging**
