### PR TITLE
Don’t hide error if cache key generation fails

### PR DESCRIPTION
**Pull request by KATT**
Whilst discovering #348 it took me quite a while to understand why I was just getting "unauthorized" in my app when it was in fact because of `hash()` failing. This change will make the real error bubble up rather than a "FORBIDDEN".

### CODE REVIEW

**Comment by maticzav** [comment]
Have you tried using `debug`?

**Comment by maticzav** [comment]
I believe this PR presents potential vulnerabilities to the permission layers created using GraphQL Shield. As mentioned, `debug` serves the purpose of uncovering hidden bugs (including the cache-key generation bug mentioned in the thread), and fulfils its role thoroughly.

To my understanding, this PR suggests moving a certain part of the code out of the Shield enclosure to make it possible for clients to see more information about the internal errors then is possible at the moment. I think this is a destructive step since it allows data from permission layer to flow out of it on edge cases when the system throws an error.

**Comment by KATT** [comment]
We should do this the way I suggested it, or introduce a more granular error for when cache key generation throws. But it's *not* an Auth error, it is an internal server error. 

I'm not the only one that have had a debugging nightmare with this - https://github.com/maticzav/graphql-shield/issues/347#issuecomment-495667624.

**Comment by P4sca1** [comment]
How about throwing the internal server error when allowExternalErrors is true and throw the fallback error otherwise?

**Comment by KATT** [comment]
Always throw internal server error for this error. It is an internal server error. Maybe you want a custom message to not leak implementation details, but disguising it as something else is a disservice that we both have banged our heads on.

**Pull request closed without merging**
