### PR TITLE
Fix: Expose Race Rule

### PR DESCRIPTION
**Pull request by victormonterrosoqb**
The documentation references the `race` rule but it is not exported.

### CODE REVIEW

**Comment by aakay** [comment]
Hi, will this PR be merged soon? I miss `race` a lot...

**Comment by maticzav** [comment]
I see that we've implemented `race` rule, there are also tests, but I can't recall writing the code itself - I do remember discussions though. I thought we hadn't made any progress with it.

Well, let me know how it works :smile:

**Comment by aakay** [comment]
Cheers guys, @maticzav for the release and @victormonterrosoqb for the fix.

🎉

**Pull request merged**
