### PR TITLE
fix(docs): Begin a "Troubleshooting" section

### PR DESCRIPTION
**Pull request by Corim**
Troubleshooting issue added based on #97

### CODE REVIEW

**Comment by maticzav** [comment]
Hey @Corim 👋!

What a great idea of adding the `Troubleshooting` section. I love your addition. The only thing I would change, if you don't mind, is the last sentence; I wouldn't say the response becomes invalid as I believe this might paint the wrong picture but rather that GraphQL sticks to its definition.

I am not sure whether we want to keep this as short as possible and only present the solution or genuinely acknowledge what happens behind the scenes. Maybe the following comment can better portray what I have in mind;

https://github.com/maticzav/graphql-shield/issues/126#issuecomment-416524581

Tell me what you think! 🙂

**Comment by Corim** [comment]
I just wanted to start by saying I think you’ve done a great job with this project!

I do agree that the last sentence should be changed.

In regards to the solution length, I think a clear, concise answer helps keep out the noise, but I also think your explanation in #126 is tremendously helpful. I’m not sure how taboo it is, but a temporary solution - resulting in the fastest buildup of a robust troubleshooting section - might be to link to the issues (in this case #126 and #97) that already have explanations and examples. These links could be changed in the future to reference a blog post or document containing a lengthy and detailed answer.

I wouldn’t say this is the “correct” method, but linking to the issues that already have written explanations would definitely be an effective method to utilize work you’ve already done (until more time can be put into writing up comprehensive answers).

Going forward, a few other troubleshooting issues that come to mind relate to caching and "trying to use the permissions system as a filter" (which obviously doesn’t work, but it did take me some time to realize why)

As a newbie, I’ve made all the now-obvious mistakes. I will commit these changes, let me know what you think.

Thanks for all the work you've done!

**Comment by maticzav** [comment]
@Corim, this is such an amazing PR! I’ll merge it right away; thanks for addressing suggestions from above.

I hope you add all the issues you can think of, let me know if you need any help! 

Thanks again 🎉

**Pull request merged**
