### PR TITLE
Replace opencollective with lightercollective.

### LINKED ISSUE #288: Switch to lightercollective
# Feature request

## Is your feature request related to a problem? Please describe

I use graphql-shield in a serverless environment where I try to optimize my bundle size to be very small. Since graphql-shield includes opencollective as a production dependency, opencollective's dependencies are also pulled in. These dependencies include `babel-polyfill`, which in turn requires `babel-polyfill`. The two of these together add 16 MB to the uncompressed bundle, which is quite a bit for code that is never actually run as part of application code. According to [lightercollective](https://github.com/WebReflection/lightercollective), the total bundle size of opencollective is 24 MB.

## Describe the solution you'd like

Switch to lightercollective—its installed size is only 4 KB.

## Describe alternatives you've considered

opencollective could also be made into an optional dependency.

## Additional context

N/A

### PR DESCRIPTION
**Pull request by ohwillie**
Resolves #288.

### CODE REVIEW

**Comment by maticzav** [comment]
@ohwillie thank you for the PR! Would you mind fixing the `lockfile` as well? I would be more than happy to merge it afterwards. 🙂

**Comment by robhanlon-c1** [comment]
@maticzav done! `package-lock.json` is in `.gitignore` so i had to force-add it—is that intentional?

**Comment by robhanlon-c1** [comment]
Oh, I just noticed that this has a `yarn.lock`. Got it! One moment.

**Comment by ohwillie** [comment]
Ah, this has a `yarn.lock`. Just a second!

**Comment by ohwillie** [comment]
Okay, updated :)

**Pull request merged**
